# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import zipfile
import shutil
import subprocess
import os
import time

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from segmentation_models_pytorch import UnetPlusPlus
from pathlib import Path
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

python_interpreter_path = "venv3/Scripts/python.exe"
prediction_script_path = "main.py"

class Ui_IceNet(object):
    def setupUi(self, IceNet):
        IceNet.setObjectName("IceNet")
        IceNet.setEnabled(True)
        IceNet.resize(737, 867)
        IceNet.setFixedSize(737, 867)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IceNet.sizePolicy().hasHeightForWidth())
        IceNet.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        IceNet.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        IceNet.setFont(font)
        IceNet.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        IceNet.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton = QtWidgets.QPushButton(IceNet)
        self.pushButton.setGeometry(QtCore.QRect(570, 70, 131, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color:rgb(128, 126, 194);\n"
                                      "    border: 1px solid;\n"
                                      "    border-color: rgb(212, 212, 212);\n"
                                      "    border-width: 1px;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover \n"
                                      "{\n"
                                      "    background-color:rgb(109, 108, 166);\n"
                                      "    border: 1px solid;\n"
                                      "    border-color: rgb(212, 212, 212);\n"
                                      "    border-width: 1px;\n"
                                      "    border-radius: 4px;\n"
                                      "}")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(IceNet)
        self.lineEdit.setGeometry(QtCore.QRect(30, 70, 531, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "    border: 1px solid;\n"
                                    "    border-color: rgb(212, 212, 212);\n"
                                    "    border-width: 2px;\n"
                                    "    border-radius: 4px;\n"
                                    "}")
        self.lineEdit.setFrame(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(IceNet)
        self.label.setGeometry(QtCore.QRect(30, 200, 301, 301))
        self.label.setStyleSheet("QLabel {\n"
                                 "    border: 1px solid;\n"
                                 "    border-color: rgb(212, 212, 212);\n"
                                 "    border-width: 2px;\n"
                                 "    border-radius: 4px;\n"
                                 "}")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(IceNet)
        self.label_2.setGeometry(QtCore.QRect(400, 200, 301, 301))
        self.label_2.setStyleSheet("QLabel {\n"
                                   "    border: 1px solid;\n"
                                   "    border-color: rgb(212, 212, 212);\n"
                                   "    border-width: 2px;\n"
                                   "    border-radius: 4px;\n"
                                   "}")
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(IceNet)
        self.label_3.setGeometry(QtCore.QRect(210, 540, 301, 301))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
                                   "    border: 1px solid;\n"
                                   "    border-color: rgb(212, 212, 212);\n"
                                   "    border-width: 2px;\n"
                                   "    border-radius: 4px;\n"
                                   "}")
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(IceNet)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 165, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 165, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(IceNet)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 120, 131, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "    background-color:rgb(128, 126, 194);\n"
                                        "    border: 1px solid;\n"
                                        "    border-color: rgb(212, 212, 212);\n"
                                        "    border-width: 1px;\n"
                                        "    border-radius: 4px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover \n"
                                        "{\n"
                                        "    background-color:rgb(109, 108, 166);\n"
                                        "    border: 1px solid;\n"
                                        "    border-color: rgb(212, 212, 212);\n"
                                        "    border-width: 1px;\n"
                                        "    border-radius: 4px;\n"
                                        "}")
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(IceNet)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 231, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(IceNet)
        self.label_6.setGeometry(QtCore.QRect(400, 170, 191, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(IceNet)
        self.label_7.setGeometry(QtCore.QRect(210, 510, 191, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(IceNet)
        QtCore.QMetaObject.connectSlotsByName(IceNet)

        self.zip_file_path = None

    def retranslateUi(self, IceNet):
        _translate = QtCore.QCoreApplication.translate
        IceNet.setWindowTitle(_translate("IceNet", "IceNet"))
        self.pushButton.setText(_translate("IceNet", "Загрузить ZIP"))
        self.pushButton.clicked.connect(self.load_zip_file)
        self.label_4.setText(_translate("IceNet", "IceNet"))
        self.pushButton_3.setText(_translate("IceNet", "Запустить"))
        self.pushButton_3.clicked.connect(self.extract_zip_file)
        self.label_5.setText(_translate("IceNet", "Радиолокационный снимок"))
        self.label_6.setText(_translate("IceNet", "Карта температур"))
        self.label_7.setText(_translate("IceNet", "Кромка льда"))



    def load_zip_file(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setFileMode(QFileDialog.ExistingFile)
        file_dialog.setOption(QFileDialog.DontUseNativeDialog, True)  # Используем старый стиль проводника файлов
        zip_file_path, _ = file_dialog.getOpenFileName(
            None, "Выберите Zip файл", "", "Zip Files (*.zip)", options=options
        )
        if zip_file_path:
            self.zip_file_path = zip_file_path
            self.lineEdit.setText(self.zip_file_path)
            print("Выбранный Zip файл:", self.zip_file_path)

            # Открываем zip файл для анализа его содержимого
            with zipfile.ZipFile(self.zip_file_path, 'r') as zip_ref:
                self.folders_to_extract = [name for name in zip_ref.namelist() if name.endswith('/')]

            print("Папки для распаковки из Zip файла:", self.folders_to_extract)


    def extract_zip_file(self):
        if self.zip_file_path:
            # Определяем текущую директорию
            current_directory = os.path.dirname(os.path.abspath(__file__))

            # Очищаем существующие папки, если они присутствуют
            for folder in self.folders_to_extract:
                target_folder = os.path.join(current_directory, folder)
                if os.path.exists(target_folder):
                    print("Очистка папки", target_folder)
                    shutil.rmtree(target_folder)

            # Распаковываем zip файл в текущую директорию
            with zipfile.ZipFile(self.zip_file_path, 'r') as zip_ref:
                zip_ref.extractall(current_directory)

            print("Zip файл успешно распакован в", current_directory)

            image_dir = os.path.join(current_directory, 'image')
            temp_dir = os.path.join(current_directory, 'temp')
            print(image_dir)
            print(temp_dir)

            image_files = [f for f in os.listdir(image_dir) if os.path.isfile(os.path.join(image_dir, f))]
            temp_files = [f for f in os.listdir(temp_dir) if os.path.isfile(os.path.join(temp_dir, f))]

            print(image_files)
            print(image_files[0])

            if image_files:
                self.image_path = os.path.join(image_dir, image_files[0])
                pixmap = QtGui.QPixmap(self.image_path)
                self.label.setPixmap(pixmap)
                self.label.setScaledContents(True)

            # Выбираем первое изображение из папки Temp
            if temp_files:
                self.temp_path = os.path.join(temp_dir, temp_files[0])
                pixmap = QtGui.QPixmap(self.temp_path)
                self.label_2.setPixmap(pixmap)
                self.label_2.setScaledContents(True)

            # Запускаем prediction.py для выполнения предсказаний
            if os.path.exists(prediction_script_path):
                print("Запуск скрипта prediction...")
                subprocess.Popen([python_interpreter_path, prediction_script_path]).wait()
                masks_dir = os.path.join(current_directory, 'predicted_masks')
                print(masks_dir)

                masks_files = [f for f in os.listdir(masks_dir) if os.path.isfile(os.path.join(masks_dir, f))]

                print(masks_dir)

                if masks_files:
                    self.masks_path = os.path.join(masks_dir, masks_files[0])
                    pixmap = QtGui.QPixmap(self.masks_path)
                    self.label_3.setPixmap(pixmap)
                    self.label_3.setScaledContents(True)
            else:
                print("Файл prediction.py не найден.")

        else:
            print("Сначала выберите Zip файл для распаковки.")





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_IceNet()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())